---
# tasks file for adipriyantobpn.repo-remi
- block:

  - name: include yum repository variable file
    include_vars: "repo-{{ repo_location }}.yml"

  - name: install REMI yum repository
    yum:
      name: "{{ remi_repoinstaller_url }}"
      state: present
    register: remi_install_result
    until: '"failed" not in remi_install_result'
    retries: 5
    delay: 10

  - name: import REMI GPG key
    rpm_key:
      key: "{{ remi_gpgkey_url.replace('file://', '') }}"
      state: present
    ignore_errors: "{{ ansible_check_mode }}"

  - name: configure REMI yum repository
    yum_repository:
      name: "{{ item.name.lower() }}"
      description: "Remi's RPM repository for Enterprise Linux $releasever - $basearch - {{ item.name }}"
      mirrorlist: "{{ item.mirrorlist | default(omit) }}"
      failovermethod: roundrobin
      baseurl: "{{ item.baseurl | default(omit) }}"
      gpgkey: "{{ remi_gpgkey_url }}"
      gpgcheck: yes
      enabled: "{{ item.enabled }}"
      file: "{{ item.file }}"
      state: present
    become: True
    with_items:
      - { name: REMI          ,file: remi         ,enabled: "{{ remi_enabled }}"        ,baseurl: "{{ remi_baseurl | default(omit) }}"        ,mirrorlist: "{{ remi_mirrorlist | default(omit) }}" }
      - { name: REMI-Safe     ,file: remi-safe    ,enabled: "{{ remi_safe_enabled }}"   ,baseurl: "{{ remi_safe_baseurl | default(omit) }}"   ,mirrorlist: "{{ remi_safe_mirrorlist | default(omit) }}" }
      - { name: REMI-PHP54    ,file: remi-php54   ,enabled: "{{ remi_php54_enabled }}"  ,baseurl: "{{ remi_php54_baseurl | default(omit) }}"  ,mirrorlist: "{{ remi_php54_mirrorlist | default(omit) }}" }
      - { name: REMI-PHP55    ,file: remi         ,enabled: "{{ remi_php55_enabled }}"  ,baseurl: "{{ remi_php55_baseurl | default(omit) }}"  ,mirrorlist: "{{ remi_php55_mirrorlist | default(omit) }}" }
      - { name: REMI-PHP56    ,file: remi         ,enabled: "{{ remi_php56_enabled }}"  ,baseurl: "{{ remi_php56_baseurl | default(omit) }}"  ,mirrorlist: "{{ remi_php56_mirrorlist | default(omit) }}" }
      - { name: REMI-PHP70    ,file: remi-php70   ,enabled: "{{ remi_php70_enabled }}"  ,baseurl: "{{ remi_php70_baseurl | default(omit) }}"  ,mirrorlist: "{{ remi_php70_mirrorlist | default(omit) }}" }
      - { name: REMI-PHP71    ,file: remi-php71   ,enabled: "{{ remi_php71_enabled }}"  ,baseurl: "{{ remi_php71_baseurl | default(omit) }}"  ,mirrorlist: "{{ remi_php71_mirrorlist | default(omit) }}" }
  become: True
