---
# tasks file for adipriyantobpn.repo-remi
- block:

  - name: include yum repository variable file
    include_vars: "repo-{{ repo_location }}.yml"

  - name: install REMI yum repository
    yum:
      name: "{{ remi_repoinstaller_url }}"
      state: present
    register: remi_install_result
    until: '"failed" not in remi_install_result'
    retries: 5
    delay: 10

  - name: import REMI GPG key
    rpm_key:
      key: "{{ remi_gpgkey_url.replace('file://', '') }}"
      state: present
    ignore_errors: "{{ ansible_check_mode }}"

  - name: configure REMI yum repository
    yum_repository:
      name: "{{ item.key.lower() }}"
      description: "{{ item.value.name }} RPM repository for Enterprise Linux $releasever - $basearch"
      mirrorlist: "{{ item.value.mirrorlist | default(omit) }}"
      failovermethod: roundrobin
      baseurl: "{{ item.value.baseurl | default(omit) }}"
      gpgkey: "{{ remi_gpgkey_url }}"
      gpgcheck: yes
      enabled: "{{ item.value.enabled }}"
      file: "{{ item.value.file }}"
      state: present
    with_dict: "{{ remi_repo }}"
  become: True
